=== saifana-km/CST1340-Group-Coursework/XML/music_store.dtd
<!--DATA SCHEMA STRUCTURE-->
<!-- Root Element -->
<!ELEMENT MusicStore (Instrument*, Vinyl*, Customer*, Employee*)> 

<!-- Child Elements -->
<!-- INSTRUMENT -->
<!ELEMENT Instrument (InstrumentName, Brand, InstrumentPrice, InstrumentImage)>
<!ATTLIST Instrument id ID #REQUIRED> <!-- Required attribute -->
<!ELEMENT InstrumentName (#PCDATA)>
<!ELEMENT Brand (#PCDATA)>
<!ELEMENT InstrumentPrice (#PCDATA)>
<!ELEMENT InstrumentImage (#PCDATA)>

<!-- VINYL -->
<!ELEMENT Vinyl (Title, Artist, Genre, VinylPrice, VinylImage)>
<!ATTLIST Vinyl id ID #REQUIRED>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Artist (#PCDATA)>
<!ELEMENT Genre (#PCDATA)>
<!ELEMENT VinylPrice (#PCDATA)>
<!ELEMENT VinylImage (#PCDATA)>

<!-- CUSTOMER -->
<!ELEMENT Customer (CustomerName, Email, Phone)>
<!ATTLIST Customer id ID #REQUIRED>
<!ELEMENT CustomerName (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>

<!-- EMPLOYEE -->
<!ELEMENT Employee (EmployeeName, Role)>
<!ATTLIST Employee id ID #REQUIRED>
<!ELEMENT EmployeeName (#PCDATA)>
<!ELEMENT Role (#PCDATA)>

=== saifana-km/CST1340-Group-Coursework/XML/music_store.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MusicStore SYSTEM "music_store.dtd">
<?xml-stylesheet type="text/xsl" href="music_store.xsl"?>

<MusicStore>
    <!-- Instruments -->
    <Instrument id="I001">
        <InstrumentName>Stratocaster</InstrumentName>
        <Brand>Fender</Brand>
        <InstrumentPrice>1499.99</InstrumentPrice>
        <InstrumentImage>images/instruments/stratocaster.webp</InstrumentImage>
    </Instrument>

    <Instrument id="I002">
        <InstrumentName>Les Paul Standard</InstrumentName>
        <Brand>Gibson</Brand>
        <InstrumentPrice>2499.99</InstrumentPrice>
        <InstrumentImage>images/instruments/le_paul_standard.jpg</InstrumentImage>
    </Instrument>

    <Instrument id="I003">
        <InstrumentName>FA-125CE</InstrumentName>
        <Brand>Fender</Brand>
        <InstrumentPrice>299.99</InstrumentPrice>
        <InstrumentImage>images/instruments/FA-125CE.webp</InstrumentImage>
    </Instrument>

    <Instrument id="I004">
        <InstrumentName>P-Bass</InstrumentName>
        <Brand>Fender</Brand>
        <InstrumentPrice>849.99</InstrumentPrice>
        <InstrumentImage>images/instruments/P-Bass.jpg</InstrumentImage>
    </Instrument>

    <Instrument id="I005">
        <InstrumentName>DW Collector's Series</InstrumentName>
        <Brand>DW Drums</Brand>
        <InstrumentPrice>3999.99</InstrumentPrice>
        <InstrumentImage>images/instruments/DW_Collectors_Series.webp</InstrumentImage>
    </Instrument>

    <!-- Vinyls -->
    <Vinyl id="V001">
        <Title>Beatopia</Title>
        <Artist>beabadoobee</Artist>
        <Genre>Indie Pop</Genre>
        <VinylPrice>29.99</VinylPrice>
        <VinylImage>images/vinyls/beebadoobee.jpg</VinylImage>
    </Vinyl>

    <Vinyl id="V002">
        <Title>Master of Puppets</Title>
        <Artist>Metallica</Artist>
        <Genre>Heavy Metal</Genre>
        <VinylPrice>24.99</VinylPrice>
        <VinylImage>images/vinyls/metallica.jpg</VinylImage>
    </Vinyl>

    <Vinyl id="V003">
        <Title>Slipknot</Title>
        <Artist>Slipknot</Artist>
        <Genre>Nu Metal</Genre>
        <VinylPrice>34.99</VinylPrice>
        <VinylImage>images/vinyls/slipknot.jpg</VinylImage>
    </Vinyl>

    <Vinyl id="V004">
        <Title>My World</Title>
        <Artist>Justin Bieber</Artist>
        <Genre>Pop</Genre>
        <VinylPrice>27.99</VinylPrice>
        <VinylImage>images/vinyls/myworld.png</VinylImage>
    </Vinyl>

    <Vinyl id="V005">
        <Title>When We Were Younger</Title>
        <Artist>grentperez</Artist>
        <Genre>Pop</Genre>
        <VinylPrice>31.99</VinylPrice>
        <VinylImage>images/vinyls/whenwewereyounger.jpg</VinylImage>
    </Vinyl>

    <Vinyl id="V006">
        <Title>Seven Goblins</Title>
        <Artist>Masayoshi Takanaka</Artist>
        <Genre>Japanese Jazz</Genre>
        <VinylPrice>19.99</VinylPrice>
        <VinylImage>images/vinyls/sevengoblins.jpg</VinylImage>
    </Vinyl>

    <Vinyl id="V007">
        <Title>New Jeans</Title>
        <Artist>NewJeans</Artist>
        <Genre>K-Pop</Genre>
        <VinylPrice>89.99</VinylPrice>
        <VinylImage>images/vinyls/newjeans.jpg</VinylImage>
    </Vinyl>

    <Vinyl id="V008">
        <Title>Feel My Rhythm</Title>
        <Artist>Red Velvet</Artist>
        <Genre>K-Pop</Genre>
        <VinylPrice>79.99</VinylPrice>
        <VinylImage>images/vinyls/redvelvet.jpg</VinylImage>
    </Vinyl>

    <!-- Customers -->
    <Customer id="C001">
        <CustomerName>Alice Monroe</CustomerName>
        <Email>alice.monroe@email.com</Email>
        <Phone>+1-555-0101</Phone>
    </Customer>

    <Customer id="C002">
        <CustomerName>James Hartley</CustomerName>
        <Email>j.hartley@email.com</Email>
        <Phone>+1-555-0234</Phone>
    </Customer>

    <Customer id="C003">
        <CustomerName>Sofia Reyes</CustomerName>
        <Email>sofia.reyes@email.com</Email>
        <Phone>+1-555-0378</Phone>
    </Customer>

    <Customer id="C004">
        <CustomerName>Daniel Park</CustomerName>
        <Email>dan.park@email.com</Email>
        <Phone>+1-555-0412</Phone>
    </Customer>

    <Customer id="C005">
        <CustomerName>Priya Nair</CustomerName>
        <Email>priya.nair@email.com</Email>
        <Phone>+1-555-0567</Phone>
    </Customer>

    <!-- Employees -->
    <Employee id="E001">
        <EmployeeName>Tom Bassett</EmployeeName>
        <Role>Store Manager</Role>
    </Employee>

    <Employee id="E002">
        <EmployeeName>Clara Hughes</EmployeeName>
        <Role>Sales Associate</Role>
    </Employee>

    <Employee id="E003">
        <EmployeeName>Marco Diaz</EmployeeName>
        <Role>Instrument Technician</Role>
    </Employee>

    <Employee id="E004">
        <EmployeeName>Yuki Tanaka</EmployeeName>
        <Role>Vinyl Specialist</Role>
    </Employee>

    <Employee id="E005">
        <EmployeeName>Lena Fischer</EmployeeName>
        <Role>Cashier</Role>
    </Employee>

</MusicStore>
